name: First Workflow

on:
  - push

jobs: 
    first_job: 
        name: jomac-k8
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "My first GitHu Actions Job"

            - name: List all Files including hidden
              run: ls -1a

            - name: Read file 
              run: pwd